# Project information
site_name: nx-dotnet
site_url: https://nx-dotnet.com
site_author: Craigory Coppola
site_description: >-
  nx-dotnet is a new nx plugin that allows
  seamless .NET application development 
  inside of an Nx Monorepo

# Repository
repo_name: nx-dotnet/nx-dotnet
repo_url: https://github.com/nx-dotnet/nx-dotnet
edit_uri: ""

docs_dir: ../../docs
site_dir: ../../dist/apps/docs-site
theme: 
  name: 'material'
  custom_dir: overrides