name: Run CI checks

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  NX_BRANCH: ${{ github.event.number }}
  NX_RUN_GROUP: ${{ github.run_id }}

jobs:
  build:
    runs-on: ubuntu-latest
    name: Building affected apps
    steps:
      - uses: actions/checkout@v1
      - uses: bahmutov/npm-install@v1.4.5
      - run: yarn nx affected -- --target=build --base=origin/master~1 --parallel
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: |
            dist

  test:
    runs-on: ubuntu-latest
    name: Testing affected apps
    steps:
      - uses: actions/checkout@v1
      - uses: bahmutov/npm-install@v1.4.5
      - run: yarn nx affected -- --target=test --base=origin/master~1 --parallel

  lint:
    runs-on: ubuntu-latest
    name: Linting affected apps
    steps:
      - uses: actions/checkout@v1
      - uses: bahmutov/npm-install@v1.4.5
      - run: yarn nx affected -- --target=lint --base=origin/master~1 --parallel

  e2e:
    runs-on: ubuntu-latest
    name: E2E testing affected apps
    steps:
      - uses: actions/checkout@v1
      - uses: bahmutov/npm-install@v1.4.5
      - run: yarn nx affected -- --target=e2e --base=origin/master~1 --parallel

  publish:
    runs-on: ubuntu-latest
    needs: build
    name: Publish affected apps
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          registry-url: 'https://registry.npmjs.org'
          always-auth: true
      - uses: bahmutov/npm-install@v1.4.5
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - run: yarn nx workspace-schematic publish-dev
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
