name: Run CI checks

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  NX_BRANCH: ${{ github.event.number }}
  NX_RUN_GROUP: ${{ github.run_id }}

jobs:

  pre-run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 3

      - name: Detect changed directories
        uses: gagle/nx-check-changes@v1.0.0
        id: nx-changes

    outputs:
      changed-dirs: ${{ steps.nx-changes.outputs.changed-dirs }}
      skip: ${{ steps.nx-changes.outputs.not-affected }}

  build:
    runs-on: ubuntu-latest
    name: Building affected apps
    needs: [pre-run]
    if: needs.pre-run.outputs.skip == 'false'
    steps:
      - uses: actions/checkout@v1
      - uses: bahmutov/npm-install@v1.4.5
      - run: yarn nx affected -- --target=build --base=origin/master~1 --parallel --with-deps
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: |
            dist

  test:
    runs-on: ubuntu-latest
    name: Testing affected apps
    needs: [pre-run]
    if: needs.pre-run.outputs.skip == 'false'
    steps:
      - uses: actions/checkout@v1
      - uses: bahmutov/npm-install@v1.4.5
      - run: yarn nx affected -- --target=test --base=origin/master~1 --parallel

  lint:
    runs-on: ubuntu-latest
    name: Linting affected apps
    needs: [pre-run]
    if: needs.pre-run.outputs.skip == 'false'
    steps:
      - uses: actions/checkout@v1
      - uses: bahmutov/npm-install@v1.4.5
      - run: yarn nx affected -- --target=lint --base=origin/master~1 --parallel

  e2e:
    runs-on: ubuntu-latest
    name: E2E testing affected apps
    needs: [pre-run, build]
    if: needs.pre-run.outputs.skip == 'false'
    steps:
      - uses: actions/checkout@v1
      - uses: bahmutov/npm-install@v1.4.5
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - run: yarn e2e

  publish:
    runs-on: ubuntu-latest
    needs: [pre-run, build]
    name: Publish affected apps
    if: ${{needs.pre-run.outputs.skip == 'false' && github.ref == 'refs/heads/master' && github.event == 'push'}}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          registry-url: 'https://registry.npmjs.org'
          always-auth: true,
          node-version: 14
      - uses: bahmutov/npm-install@v1.4.5
      - name: Git Config
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - run: yarn ts-node tools/scripts/publish-dev
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          tags: true
