name: Run PR checks

on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  main:
    name: Nx Cloud - Main Job
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.2
    with:
      main-branch-name: 'master'
      parallel-commands: |
        npx nx-cloud record yarn nx workspace-lint
        npx nx-cloud record yarn nx format:check
        npx nx-cloud record yarn documentation:check --verbose
        npx nx-cloud record yarn commitlint --from ${{ github.event.pull_request.base.sha }} --to HEAD --verbose
      parallel-commands-on-agents: |
        yarn nx affected -- --target=lint --base=origin/master --parallel 3
        yarn nx affected -- --target=build --base=origin/master --parallel 3
        yarn nx affected -- --target=test --base=origin/master --parallel 3
      final-commands: |
        yarn e2e

  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.2
    with:
      number-of-agents: 3
