name: Release

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    name: Building affected apps
    steps:
      - uses: actions/checkout@v1
      - uses: bahmutov/npm-install@v1.4.5
      - run: yarn nx affected --target=build --base=origin/master~1 --parallel
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

  e2e:
    runs-on: ubuntu-latest
    name: E2E testing affected apps
    needs: [build]
    steps:
      - uses: actions/checkout@v1
      - uses: bahmutov/npm-install@v1.4.5
      - name: Download a single artifact
        continue-on-error: true
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - run: yarn e2e
      - run: git reset --hard

  semantic-release:
    runs-on: ubuntu-latest
    name: Publish packages via semantic release
    needs: [e2e]
    if: ${{github.event_name == 'workflow_dispatch'}}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          registry-url: 'https://registry.npmjs.org'
          always-auth: true,
          node-version: 16
      - uses: bahmutov/npm-install@v1.4.5
      - name: Git Config
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - name: Setup NPM Auth
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
          npm whoami
      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          VERBOSE_LOGGING: 'true'

  post-release-smoke-tests:
    uses: nx-dotnet/nx-dotnet/.github/workflows/smoke.yml@master
    name: Run smoke tests post-release
    needs: [semantic-release]